"""
File Name: VMData
Description: Configuration values to the variables to setup the new VM and install Control suite and Equitrac
"""
cred_file_path = 'C:\git-repo\dj_poc\AutomationPOC\setup_infra\In_creds'
psFile_path = "C:\git-repo\dj_poc\AutomationPOC\setup_infra\eqsetup_v1.ps1"
csCoreCompVersion = ""
folder_IVT = ""
folder_columbus = ""
folder_vasco = ""
vmHost = "
datastore_ivt = ""
datastore_server = ""
template_win2k16 = ""
template_win2k12r2 = "
template_win2k12 = ""
domain_name = ""
vm_name_prefix = "auto-"
domain_admin_name = ""
domain_admin_pwd = ""
domain_user = "
domain_pwd = ''
VM_user_name = ""
VM_user_pwd = ""
cs_installer_base_path = "\\\\folder\\path"
cs_core_comp_version = ""
eq_base_path = "\\\\folder-eq\\path-eq\\"
os_cus_spec = "OSAuto"
main_base_path = "\\\\directory\\folder\\" 
files_to_copy = "abc.msi"
